# Generated by Django 5.1.4 on 2024-12-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('size', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('age_limit', models.BooleanField(default=False)),
                ('buyer', models.ManyToManyField(default=None, related_name='games', to='task_one.buyer')),
            ],
        ),
    ]
